platform: Any CPU
configuration: Release

before_build:
  - nuget restore Source\Code\ProjectPlugins.sln

image: Visual Studio 2017
  
build:
  project: Source\Code\ProjectPlugins.sln
  verbosity: minimal
  publish_nuget: true

branches:
  except:
    - duality3
